CREATE SEQUENCE SEQ_USER 
INCREMENT BY 1
START WITH 1
MINVALUE 1
MAXVALUE 1000;

CREATE SEQUENCE SEQ_BOOK
INCREMENT BY 1
START WITH 1000
MINVALUE 1
MAXVALUE 10000;

CREATE SEQUENCE SEQ_RENTAL
INCREMENT BY 1
START WITH 10000
MINVALUE 1
MAXVALUE 100000;

CREATE TABLE TL_USER (
	USER_NUMBER NUMBER,				--회원번호
	PHONE_NUMBER VARCHAR2(20),  	--PHONE_NUMBER
	PW VARCHAR2(20),				--비밀번호
	NAME VARCHAR2(20),				--이름
	AGE NUMBER(2),					--나이
	CONSTRAINT PK_USERNUM PRIMARY KEY(USER_NUMBER),
	CONSTRAINT UN_PHONENUM UNIQUE (PHONE_NUMBER)
);

CREATE TABLE TL_BOOK (
	BOOK_NUMBER NUMBER,								--도서번호
	BOOK_NAME VARCHAR2(100) NOT NULL,				--도서명
	AUTHOR VARCHAR2(100) NOT NULL,					--저자
	COMPANY VARCHAR2(50) NOT NULL,					--출판사
	BOOK_DATE DATE NOT NULL,						--출판일
	BOOK_SECTION VARCHAR2(20),						--도서 위치
	BOOK_RENTAL VARCHAR2(20) DEFAULT '대여가능',		--대여 여부('대여중','대여가능')
	RENTAL_COUNT NUMBER DEFAULT 0,
	CONSTRAINT PK_BOOK PRIMARY KEY(BOOK_NUMBER)
);

CREATE TABLE TL_RENTAL (
	NAME VARCHAR2(20),			--회원이름
	USER_NUMBER NUMBER, 		--(서브쿼리)USER_NUMBER로 PHONE_NUMBER가져오기
	BOOK_NUMBER NUMBER,			--도서번호
	BOOK_NAME VARCHAR2(100),		--도서명
	RENTAL_DATE DATE,			--대여일 (SYSDATE)
	RETURN_DATE DATE,			--반납일 (SYSDATE + 7)
	CONSTRAINT FK_USER_NUMBER FOREIGN KEY (USER_NUMBER) REFERENCES TL_USER (USER_NUMBER),
	CONSTRAINT FK_BOOK_NUMBER FOREIGN KEY (BOOK_NUMBER) REFERENCES TL_BOOK (BOOK_NUMBER)
);

TRUNCATE TABLE TL_RENTAL;
TRUNCATE TABLE TL_BOOK;
TRUNCATE TABLE TL_USER;

SELECT * FROM TL_USER;
SELECT * FROM TL_BOOK;
SELECT * FROM TL_RENTAL;

DROP TABLE TL_BOOK;
DROP TABLE TL_USER;
DROP TABLE TL_RENTAL;